# Generated by Django 4.1.3 on 2022-12-04 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planets', '0001_init'),
        ('affects', '0001_init'),
        ('adventures', '0001_init'),
        ('creatures', '0001_init'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='adventures.adventure')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='planets.planet')),
            ],
        ),
        migrations.CreateModel(
            name='Battler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battlers', to='adventures.adventure')),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='creatures.creature')),
                ('weapon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='affects.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='BattleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allies_power', models.PositiveIntegerField()),
                ('opponents_power', models.PositiveIntegerField()),
                ('battle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='battles.battle')),
            ],
        ),
        migrations.CreateModel(
            name='BattlerEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='battles.battle')),
                ('battler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='battles.battler')),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='affects.effect')),
            ],
        ),
        migrations.CreateModel(
            name='BattleMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_opponent', models.BooleanField()),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='battles.battle')),
                ('battler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='battles.battler')),
            ],
        ),
        migrations.AddConstraint(
            model_name='battler',
            constraint=models.UniqueConstraint(fields=('creature', 'adventure'), name='creature_to_adv_unique'),
        ),
    ]
