# Generated by Django 4.1.3 on 2022-12-04 18:39

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('planets', '0001_init'),
        ('battles', '0001_init'),
        ('adventures', '0001_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammate',
            name='battler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                    to='battles.battler'),
        ),
        migrations.AddField(
            model_name='teammate',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teammates',
                                    to='adventures.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='adventure',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adventures.adventure'),
        ),
        migrations.AddField(
            model_name='adventure',
            name='planets',
            field=models.ManyToManyField(related_name='+', to='planets.planet'),
        ),
    ]
