# Generated by Django 4.1.3 on 2022-12-04 18:59

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('planets', '0001_init'),
        ('adventures', '0002_init'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventure',
            name='planets',
        ),
        migrations.CreateModel(
            name='AdventurePlanet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visited', models.BooleanField(default=False)),
                ('adventure',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventure_planets',
                                   to='adventures.adventure')),
                ('planet',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='planets.planet')),
            ],
        ),
    ]
