# Generated by Django 4.1.3 on 2022-12-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0003_is_visited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='is_successful',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
