# Generated by Django 4.1.3 on 2023-12-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0004_mullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
